<!-- src/views/kitchen/constructor/ConstructorScreen.vue -->
<template>
  <div class="constructor-screen">
    <!-- Step indicators -->
    <div class="step-header">
      <h2>CONSTRUCTOR</h2>
      <div class="step-indicators">
        <v-btn
          v-for="s in steps"
          :key="s.number"
          :color="currentStep === s.number ? 'primary' : undefined"
          :variant="currentStep === s.number ? 'flat' : 'outlined'"
          size="small"
          class="step-btn"
          @click="currentStep = s.number"
        >
          {{ s.number }}. {{ s.label }}
        </v-btn>
      </div>
    </div>

    <!-- Step content -->
    <div class="step-content">
      <StepBaseInfo
        v-if="currentStep === 1"
        v-model:name="wizardState.name"
        v-model:department="wizardState.department"
        v-model:category-id="wizardState.categoryId"
        v-model:description="wizardState.description"
        @next="currentStep = 2"
      />

      <StepComposition
        v-else-if="currentStep === 2"
        v-model:ingredients="wizardState.ingredients"
        v-model:modifier-groups="wizardState.modifierGroups"
        @back="currentStep = 1"
        @next="currentStep = 3"
      />

      <StepPreview
        v-else-if="currentStep === 3"
        :wizard-state="wizardState"
        :saving="saving"
        @back="currentStep = 2"
        @save="handleSave"
        @save-draft="handleSaveDraft"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useSnackbar } from '@/composables/useSnackbar'
import type { Department, ModifierGroup } from '@/stores/menu/types'
import type { RecipeComponent } from '@/stores/recipes/types'
import StepBaseInfo from './steps/StepBaseInfo.vue'
import StepComposition from './steps/StepComposition.vue'
import StepPreview from './steps/StepPreview.vue'

export interface WizardState {
  name: string
  department: Department
  categoryId: string | null
  description: string
  ingredients: RecipeComponent[]
  modifierGroups: ModifierGroup[]
}

const steps = [
  { number: 1, label: 'Base Info' },
  { number: 2, label: 'Composition' },
  { number: 3, label: 'Preview' }
]

const currentStep = ref(1)
const saving = ref(false)

const wizardState = reactive<WizardState>({
  name: '',
  department: 'kitchen',
  categoryId: null,
  description: '',
  ingredients: [],
  modifierGroups: []
})

async function handleSave() {
  await saveConstructorItem(true)
}

async function handleSaveDraft() {
  await saveConstructorItem(false)
}

/**
 * Save flow:
 * 1. Build RecipeComponent[] from wizard ingredients
 * 2. Call recipesStore.createRecipe() -> get recipe.id
 * 3. Create MenuItem with variant composition: [{ type: 'recipe', id: recipe.id, quantity: 1, unit: 'portion' }]
 *
 * Category mapping:
 * - MenuItem.categoryId -> menu_categories UUID (user picks in Step 1)
 * - Recipe.category -> recipe_categories UUID (auto-inferred from department via key lookup)
 */
async function saveConstructorItem(isActive: boolean) {
  if (saving.value) return
  saving.value = true

  const { useRecipesStore } = await import('@/stores/recipes')
  const { useMenuStore } = await import('@/stores/menu')
  const recipesStore = useRecipesStore()
  const menuStore = useMenuStore()
  const { showSuccess, showError } = useSnackbar()

  // Resolve recipe category UUID from department using recipe_categories table
  const departmentToKey: Record<string, string> = {
    kitchen: 'main_dish',
    bar: 'beverage'
  }
  const categoryKey = departmentToKey[wizardState.department] || 'main_dish'
  const recipeCategory = (recipesStore.recipeCategories as any[]).find(
    (c: any) => c.key === categoryKey
  )
  const recipeCategoryId = recipeCategory?.id || categoryKey // Fallback to key if not found

  let newRecipe: any = null

  try {
    // Step 1: Create Recipe
    const recipeData = {
      name: wizardState.name,
      code: '', // Auto-generated by store
      description: wizardState.description || undefined,
      category: recipeCategoryId,
      department: wizardState.department,
      portionSize: 1,
      portionUnit: 'portion',
      difficulty: 'medium' as const
    }

    newRecipe = await recipesStore.createRecipe(recipeData)
    if (!newRecipe) throw new Error('Failed to create recipe')

    // Step 1b: Add components via updateRecipe
    if (wizardState.ingredients.length > 0) {
      await recipesStore.updateRecipe(newRecipe.id, {
        components: wizardState.ingredients
      })
    }

    // Step 2: Create MenuItem with recipe reference in composition
    const dishType = wizardState.modifierGroups.length > 0 ? 'modifiable' : 'simple'
    const menuType = wizardState.department === 'kitchen' ? 'food' : 'beverage'

    const menuItemData = {
      name: wizardState.name,
      categoryId: wizardState.categoryId || '',
      type: menuType as 'food' | 'beverage',
      department: wizardState.department,
      dishType: dishType as 'simple' | 'modifiable',
      variants: [
        {
          name: 'Standard',
          price: 0, // Kitchen creates structure, admin sets price
          composition: [
            {
              type: 'recipe' as const,
              id: newRecipe.id,
              quantity: 1,
              unit: 'portion' as const
            }
          ],
          isActive
        }
      ],
      modifierGroups: wizardState.modifierGroups.length > 0 ? wizardState.modifierGroups : undefined
    }

    await menuStore.addMenuItem(menuItemData)

    showSuccess(`"${wizardState.name}" created successfully`)

    // Reset wizard
    wizardState.name = ''
    wizardState.description = ''
    wizardState.ingredients = []
    wizardState.modifierGroups = []
    currentStep.value = 1
  } catch (error) {
    // Rollback: if recipe was created but menu item failed, clean up
    if (newRecipe?.id) {
      try {
        await recipesStore.deleteRecipe(newRecipe.id)
      } catch (rollbackError) {
        console.error('Rollback failed — orphaned recipe:', newRecipe.id, rollbackError)
      }
    }
    const msg = error instanceof Error ? error.message : 'Save failed'
    showError(msg)
    console.error('Constructor save failed:', error)
  } finally {
    saving.value = false
  }
}
</script>

<style scoped lang="scss">
.constructor-screen {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.step-header {
  padding: 16px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.12);

  h2 {
    font-size: 1.1rem;
    font-weight: 600;
    margin-bottom: 8px;
  }
}

.step-indicators {
  display: flex;
  gap: 8px;
}

.step-btn {
  text-transform: none;
  font-weight: 500;
}

.step-content {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}
</style>
