-- Function: get_product_variance_report_v4
-- Description: Product Variance Report with full stock movement tracking
-- Version: v4.1 (2026-03-10)
--
-- CHANGELOG:
-- v3.0: Initial version with theoretical sales from orders
-- v3.1: Added inventory_snapshots for opening stock
-- v3.2: Fixed portion_size usage in products_in_active_preps
-- v3.3: Fixed products_from_preparations - prep_qty is PORTIONS, not grams
-- v3.4: Handle BOTH portion-type and weight-type preparations correctly
-- v4.0: Clean refactoring with cleaner CTE organization
-- v4.1: CRITICAL FIX - portion_size unit normalization for portion-type preparations
--   - recipe_prep_orders/direct_prep_orders now normalize to GRAMS
--   - Recursive sub-prep decomposition handles portion/gram units
--   - Was under-counting Sales by factor of portion_size (e.g., 30x for Salmon)
--   - All 6 functions updated: report_v4, theoretical_sales, decomposition_factors,
--     writeoffs_decomposed, loss_decomposed, inpreps
--
-- Key formulas:
-- - Expected = Opening + Received - Sales - Loss + Gain
-- - Actual = Closing + InPreps
-- - Variance = Actual - Expected (positive = surplus, negative = shortage)
--
-- Migration: src/supabase/migrations/194_fix_variance_portion_size_bug.sql
-- Store: src/stores/analytics/varianceReportStore.ts (generateReportV2 function)
--
-- For full SQL implementation, see the migration file.
