-- Function: get_product_variance_report_v4
-- Description: Product Variance Report with full stock movement tracking
-- Version: v4.0 (2026-02-02)
--
-- CHANGELOG:
-- v3.0: Initial version with theoretical sales from orders
-- v3.1: Added inventory_snapshots for opening stock
-- v3.2: Fixed portion_size usage in products_in_active_preps
-- v3.3: Fixed products_from_preparations - prep_qty is PORTIONS, not grams
-- v3.4: Handle BOTH portion-type and weight-type preparations correctly
-- v4.0: Clean refactoring with cleaner CTE organization
--   - Same calculations as v3 (verified matching results)
--   - Cleaner code structure
--   - Helper functions available for details_v3
--
-- Key concepts:
-- - Write-offs = sales_consumption (products + decomposed preparations)
-- - Loss = expired/spoiled/other (products + decomposed preparations) + negative corrections
-- - Gain = positive corrections
--
-- Key formulas:
-- - Expected = Opening + Received - Sales - Loss + Gain
-- - Actual = Closing + InPreps
-- - Variance = Actual - Expected (positive = surplus, negative = shortage)
--
-- Decomposition:
-- When a preparation is written off (sales_consumption or loss), it gets
-- decomposed recursively to its constituent products for accurate tracking.
--
-- Helper functions (for single-product queries in details_v3):
-- - calc_product_theoretical_sales(product_id, start_date, end_date)
-- - calc_product_writeoffs_decomposed(product_id, start_date, end_date)
-- - calc_product_loss_decomposed(product_id, start_date, end_date)
-- - calc_product_inpreps(product_id)
--
-- Migration: src/supabase/migrations/131_variance_report_v4.sql
-- Store: src/stores/analytics/varianceReportStore.ts (generateReportV2 function)
--
-- For full SQL implementation, see the migration file.
